spring:
  application:
    name: ootd-backend
  webmvc:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"

gemini:
  api:
    key: ${GEMINI_API_KEY}

aws:
  dynamodb:
    region: ap-northeast-2
    endpoint: http://localhost:8000

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.trion.ootd: INFO
    org.springframework: WARN
